= Taxonomic Infrastructure
:icons: font
:iconfont-cdn: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css
:stylesdir: resources/style/
:stylesheet: asciidoctor.css
:description: NSL Service
:keywords: documentation, Grails, National Species List, Taxonomy, Taxonomic
:links:
:sectlinks:
:toc: left
:toclevels: 2
:toc-class: toc2

This is the NSL (National Species List) Services Application developed at the Australian National Botanic Gardens in
association with CHAH, the ALA and the IBIS team.

== Services

The NSL services provide a relatively generic set of services for searching Names, References and Authors as well as
accessing classification trees of taxons.

The NSL is (and probably always will be) a work in progress, we'll be adding a roadmap and more doco here as we go.

This code is Licensed under the Apache 2 License and we welcome contributions from the taxonomic community.

Please use Github issues for any bug reports.

== Shard ID ranges

For Australian NSL infrastructure we are splitting the ID ranges used across different known shards. This is *not* essential
but it does mean we have a means to discriminate data sources on IDs if somehow we manage to loose track.

The current allocated ranges are:

* Vascular (APNI) 1000 - 10,000,000 + 50,000,001 - 60,000,000
* Moss 10,000,001 - 20,000,000
* Algae 20,000,001 - 30,000,000
* Lichen 30,000,001 - 40,000,000
* DAWR 40,000,001 - 50,000,000 (Aust. Dept. of Agriculture and Water Resources)
* Fungi 60,000,001 - 70,000,000

There is a confluence page for the NSL infrastructure as well at https://www.anbg.gov.au/ibis25/pages/viewpage.action?spaceKey=NSL&title=NSL+Project+2.0

== Building and Running

This is a standard https://grails.org/[Grails] 3.3.10 project. You can use all the standard grails tasks to build and run
this project. You may need some supporting services i.e.

. A mapper
. postgresql database with the NSL schema loaded

To run the services in development mode just run `grails run` which will run up the service in it's own tomcat instance
locally. You can also use the gradle task `bootRun` e.g. `./gradlew bootRun`.

The services work nicely within IntelliJ IDEA just import the project.

To build a war file you can use `grails war` or you can use `./gradlew assemble`. This will build a war file and put it
in the `build/libs` directory.

To publish to docker use the gradle task `./gradlew dockerPublish`. Note you will have to be logged into docker hub to
publish. Note we're currently publishing to pmcneil/



