package au.org.biodiversity.nsl

import spock.lang.Specification

/**
 * User: pmcneil
 * Date: 12/07/18
 *
 */
class TextDiffTest extends Specification {

    def "Diff strings"() {
        when: "I create a diff of two strings"
        TextDiff diffForward = new TextDiff(a, b)
        TextDiff diffBackward = new TextDiff(b, a)
        println "fwd: ${diffForward.chunks.size()}, Bwd: ${diffBackward.chunks.size()}"

        println diffBackward.diffHtml('span', 'red')
        println diffForward.diffHtml('span', 'green')

        then:
        diffForward.chunks.size() == chunks
        diffBackward.diffHtml('span', 'red') == html

        where:
        a                                                                                                                                                                                                                                            | b                                                                                                                                                                                                                                                                                             | chunks | html
        "but not known from Australia."                                                                                                                                                                                                              | "but not known to occur in Australia."                                                                                                                                                                                                                                                        | 5      | "but not known <span class=\"red\">from</span> <span class=\"red\"> </span>Australia."
        "Hybrids between R. millanii"                                                                                                                                                                                                                | "Hybrids between <i>R. millanii"                                                                                                                                                                                                                                                              | 3      | "Hybrids between <span class=\"red\"> </span>R. millanii"
        "Treated as Rhoeo spathacea on CoI and ChI by D.J.Du Puy & I.R.Telford, Fl. Australia 50: 442 (1993)."                                                                                                                                       | "Treated as <i>Rhoeo spathacea</i> on CoI and ChI by D.J.Du Puy & I.R.Telford in A.J.G.Wilson (ed.), <i>Fl. Australia</i> 50: 442 (1993)."                                                                                                                                                    | 11     | "Treated as <span class=\"red\"> </span>Rhoeo spathacea<span class=\"red\"> </span> on CoI and ChI by D.J.Du Puy &amp; I.R.Telford<span class=\"red\"> </span>, <span class=\"red\"> </span>Fl. Australia<span class=\"red\"> </span> 50: 442 (1993)."
        "An Asian taxon listed by J.D.Hooker in the introductory essay to <i>Fl. Tasman.</i> 2: xlvi (1859), but not known from Australia."                                                                                                          | "An Asian taxon listed by J.D.Hooker in the introductory essay to <i>Fl. Tasman.</i> 2: xlvi (1859), but not known to occur in Australia."                                                                                                                                                    | 5      | "An Asian taxon listed by J.D.Hooker in the introductory essay to &lt;i&gt;Fl. Tasman.&lt;/i&gt; 2: xlvi (1859), but not known <span class=\"red\">from</span> <span class=\"red\"> </span>Australia."
        "Subspecies are not currently recognised in this taxon in SA."                                                                                                                                                                               | "Infraspecific rank not recognised in SA."                                                                                                                                                                                                                                                    | 8      | "<span class=\"red\">Subspecies</span> <span class=\"red\">are</span> not <span class=\"red\">currently </span>recognised in <span class=\"red\">this taxon in </span>SA."
        "Treated as <i>Zoysia matrella</i> subsp. <i>matrella</i> on CoI and ChI by D.J.Du Puy & I.R.H.Telford, <i>Fl. Australia</i> 50: 482 (1993)."                                                                                                | "Treated as <i>Zoysia matrella</i> subsp. <i>matrella</i> on CoI and ChI by D.J.Du Puy & I.R.H.Telford in A.E.Orchard (ed.), <i>Fl. Australia</i> 50: 482 (1993)."                                                                                                                            | 3      | "Treated as &lt;i&gt;Zoysia matrella&lt;/i&gt; subsp. &lt;i&gt;matrella&lt;/i&gt; on CoI and ChI by D.J.Du Puy &amp; I.R.H.Telford<span class=\"red\"> </span>, &lt;i&gt;Fl. Australia&lt;/i&gt; 50: 482 (1993)."
        "The status of this taxon in the NT is uncertain. It may be native, or represent an early introduction."                                                                                                                                     | "The status of this taxon in the NT is uncertain.  It may be native, or represent an early introduction."                                                                                                                                                                                     | 3      | "The status of this taxon in the NT is uncertain. <span class=\"red\"> </span>It may be native, or represent an early introduction."
        "A hybrid taxon possibly involving <i>Crataegus crus-galli</i> and <i>C. mexicana</i> Moc & Sesse ex DC. (J.B.Phipps, <i>pers. comm.</i> 2009)."                                                                                             | "A hybrid taxon possibly involving <i>Crataegus crus-galli</i> and <i>C. mexicana</i> Moc & Sesse ex DC. (J.B.Phipps, <i>pers. comm.</i> 2009). Recorded from SA by F.J.Richardson et al., <i>Weeds of the South-East</i>, 2nd edn 451 (2011), but not known to be naturalised in Australia." | 2      | "A hybrid taxon possibly involving &lt;i&gt;Crataegus crus-galli&lt;/i&gt; and &lt;i&gt;C. mexicana&lt;/i&gt; Moc &amp; Sesse ex DC. (J.B.Phipps, &lt;i&gt;pers. comm.&lt;/i&gt; 2009)."
        "For details of the nomenclatural history of <i>Ixora triflora</i> Benth. see D.J. McGillivray, <i>Contr. New South Wales Natl. Herb.</i> 4(5): 263 (1972) and S.T.Reynolds & P.I.Forster., <i>Austrobaileya</i> 7(1): 47 (2005); 7(2) 266." | "For details of the nomenclatural history of <i>Ixora triflora</i> R,Br. ex Benth. see D.J. McGillivray, <i>Contr. New South Wales Natl. Herb.</i> 4(5): 263 (1972) and S.T.Reynolds & P.I.Forster, <i>Austrobaileya</i> 7(1): 47 (2005); 7(2) 266."                                          | 5      | "For details of the nomenclatural history of &lt;i&gt;Ixora triflora&lt;/i&gt; <span class=\"red\"> </span>Benth. see D.J. McGillivray, &lt;i&gt;Contr. New South Wales Natl. Herb.&lt;/i&gt; 4(5): 263 (1972) and S.T.Reynolds &amp; P.I.Forster<span class=\"red\"> </span>.<span class=\"red\">, &lt;i&gt;Austrobaileya&lt;/i&gt; 7(1): 47 (2005); 7(2) 266.</span>"
        "Treated as Vacoparis laxiflorum in Qld."                                                                                                                                                                                                    | "Treated as <i>Vacoparis laxiflorum</i> in Qld."                                                                                                                                                                                                                                              | 5      | "Treated as <span class=\"red\"> </span>Vacoparis laxiflorum<span class=\"red\"> </span> in Qld."
        "Records of this species in Queensland (e.g. McGillivray & Makinson, 1993) refer to G. hockingsii."                                                                                                                                          | "Records of this species in Queensland (e.g. McGillivray & Makinson, 1993) refer to <i>G. hockingsii</i>."                                                                                                                                                                                    | 5      | "Records of this species in Queensland (e.g. McGillivray &amp; Makinson, 1993) refer to <span class=\"red\"> </span>G. hockingsii<span class=\"red\"> </span>."
        "Hybrids between R. millanii and other species (R. graniticola, R. collinus and R. victoriensis) have been given the name R. ligulatus."                                                                                                     | "Hybrids between <i>R. millanii</i> and other species (<i>R. graniticola</i>, <i>R. collinus</i> and <i>R. victoriensis</i>) have been given the name <i>R. ligulatus</i>."                                                                                                                   | 21     | "Hybrids between <span class=\"red\"> </span>R. millanii<span class=\"red\"> </span> and other species (<span class=\"red\"> </span>R. graniticola<span class=\"red\"> </span>, <span class=\"red\"> </span>R. collinus<span class=\"red\"> </span> and <span class=\"red\"> </span>R. victoriensis<span class=\"red\"> </span>) have been given the name <span class=\"red\"> </span>R. ligulatus<span class=\"red\"> </span>."
        "Hybrids are recorded between E. cladocalyx and E. peninsularis (Nicolle et al., 2006)."                                                                                                                                                     | "Infraspecific identity of plants naturalised in Vic is uncertain."                                                                                                                                                                                                                           | 18     | "<span class=\"red\">Hybrids</span> <span class=\"red\">are</span> <span class=\"red\">recorded</span> <span class=\"red\">between</span> <span class=\"red\">E.</span> <span class=\"red\">cladocalyx</span> <span class=\"red\">and</span> <span class=\"red\">E.</span> <span class=\"red\">peninsularis (Nicolle et al</span>.<span class=\"red\">, 2006).</span>"
        "A putative hybrid involving <i>Eucalyptus ovata</i> and <i>E. viminalis</i>."                                                                                                                                                               | "A putative hybrid involving <i>Eucalyptus camaldulensis</i> subsp. <i>camaldulensis</i> and either <i>E. ovata</i> or <i>E. viminalis</i> subsp. <i>cygnetensis</i> (see D.Nicolle, <i>Fl. S. Australia</i> 5th edn 27 (2014)."                                                              | 8      | "A putative hybrid involving &lt;i&gt;Eucalyptus <span class=\"red\"> </span>ovata&lt;/i&gt; <span class=\"red\">and</span> &lt;i&gt;E. viminalis&lt;/i&gt;<span class=\"red\"> </span>."
        "SA (formerly now extinct?), Qld, NSW, ACT, Vic, Tas"                                                                                                                                                                                        | "SA (native and uncertain origin), Qld, NSW, ACT, Vic, Tas"                                                                                                                                                                                                                                   | 7      | "SA (<span class=\"red\">formerly</span> <span class=\"red\">now</span> <span class=\"red\">extinct? </span>), Qld, NSW, ACT, Vic, Tas"
    }

}

