version: '3.7'

services:

  mapper:
    image: biodiversity/nsl-mapper:2.0
    ports:
      - 7070:8080
    environment:
      DATABASE_USER: nsl
      DATABASE_PASSWORD: nsl
      DATABASE_URL: "${DB_HOST}/nsl"
      BASE_DOMAIN: "${BASE_DOMAIN}"
      DOMAIN_PREFIX: "${DOMAIN_PREFIX}"
      DOMAIN_PREFIX_DASH: "${DOMAIN_PREFIX_DASH}"
    volumes:
      - "${VOLUME_ROOT}/etc/nsl:/etc/nsl:ro"
    labels:
      au.org.biodiversity.description: "Mapper"

  ldap:
    image: biodiversity/nsl-ldap:1.0
    ports:
      - 10389:10389
    volumes:
      - "${VOLUME_ROOT}/etc/instances:/apacheds/instances"
    labels:
      au.org.biodiversity.description: "LDAP"

  editor:
    image: biodiversity/nsl-editor:1.88-SNAP
    ports:
      - 3000:8080
    volumes:
      - "${VOLUME_ROOT}/etc/nsl:/etc/nsl:ro"
    environment:
      EDITOR_CONFIG_FILE: /etc/nsl/editor-config.rb
      EDITOR_CONFIGDB_FILE: /etc/nsl/editor-database.yml
      SECRET_KEY_BASE: fred
      DATABASE_USER: nsl
      DATABASE_PASSWORD: nsl
      EXT_MAPPER_HOST: "${BASE_DOMAIN}:7070/broker/"
      DATABASE_URL: "${DB_HOST}/nsl"
      EXT_HOST: "${HOST_ADDR}"
      SHARD: vasc
