= Changelog
:imagesdir: resources/images/
:toc: left
:toclevels: 4
:toc-class: toc2
:icons: font
:iconfont-cdn: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css
:stylesdir: resources/style/
:stylesheet: asciidoctor.css
:description: Services Configuration
:keywords: documentation, NSL, change log
:links:
:numbered:

== v 1.0226

* Fix API and Auth interceptor tests
* NSL-3328 format isoPublicationDate for citations (cross port)
* Update to use the new mapper-mn with JWT and changes to API 
* *Removed the link cache*
* Documentation updates. 
 ** Added change log 
 ** Added config.adoc 
 ** Added docker.adoc 
* NSL-3356 changes to get diff output working again.

== v 1.0225

* NSL-3356 improve diff output to make it easier to see changes Increase the number of synonym changes shown on screen
to 100 (which may be reverted). 
* Fix search on apni-format and apc-format pages Add a docker file to build docker image Make the config file
configurable via an environment variable 
* NSL-3356 add an ordering report for synonymy on an instance that you can get from the check synonymy report. Add back
the moved indicator on the synonymy diff output. 
* Change nsl-domain plugin version to 3.1.19-SNAPSHOT to determine the grails version of the plugin to use. 
* set the version to the G2 version of the services. 
* update the nsl-domain-plugin to 1.19.SNAPSHOT due to change in the domain plugin. 

== v 1.0224 - initial grails 3 version

* Clean up audit UI and move to grails-shiro 3.1 release 
* Add readme 
* Fix classifications page layout. 
* Make the runAs user check the roles of the user being runAs Make gradle give us enough memory. 
* Get basic API realm going again. 
* Improve the content display area and keep the header constant. 
* Fix NSL-3348 and move to domain plugin 1.19-SNAPSHOT 
* Make dashboard collapse on summary data work again 
* Clean up name check page. make search pages and heading not jump when reloading 
* Clean up make consistent api calls 
* Fix some broken links. Fix missing injected dependency in NameControllerSpec 
* Port changes from grails 2 master. 
* Clean up 
* Further improve the admin log output. replace all services usage of runAsync 
* minor doc fix 
* Fix admin page log pain by finding the correct logger. Add log paths to the configuration tab. Refactor the name service
to use promises in place of runAsync and fix session related issues in batch update. Convert most of the icnNameConstruction
to CompileStatic. Make the output of a name construction service return a ConstructedName object. Remove the ApcTreeService
which related to the old tree! 
* Make the admin page tabs work again, clean up the config page output. Make the service mode redirect properly. 
* Get tests working Get most of the UI back working (except admin) Get responses going again 
* Fix up remaining page styles for index page etc. Get the tree version diff/merge/validate pages going. remove the
format interceptor as grails now handles it sensibly change the default response for diff/merge/validate make active
navigation page simpler and move name check to the main navigation from the search. 
* Refactor for changed and missing plugins, e.g. Shiro changes filters to Interceptors. Refactor general grails 3
changes such as packages make external JS libs load via CDNs and update to latest versions. Fix Bootstrap 3 -> 4 layout
issues Remove currently broken or unused features like sparql search and generic search. Split the search into name and
taxanomic and handle product URLs by redirecting to name/taxa searches to simplify logic. 
* initial commit for grails 3 version 