= Import mapper links into the mapper from a new shard
v1.0, August 2017
:imagesdir: resources/images/
:toc: left
:toclevels: 4
:toc-class: toc2
:icons: font
:iconfont-cdn: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css
:stylesdir: resources/style/
:stylesheet: asciidoctor.css
:description: Importing links into the mapper
:keywords: documentation, NSL, APNI, API, APC, tree
:links:
:numbered:

This documents the process of importing links into the mapper from a new shard that has been pre populated with data.

== Background

Shards may be populated by domain experts with data for the names, authors, references, and instances. When a name or
instance is displayed in the services it asks the mapper for the permalink to a particular resource. The Mapper is the
keeper of links and is the broker for service that can provide the information about the Linked object in the requested
format (e.g. HTML, JSON, XML, RDF)

If the mapper doesn't have a link for that resource the services will ask the mapper to add one, and claim ownership of
that object. If you are returning thousands of objects with no link in the mapper then this may take a while as it checks
each one, gets a 404 and then adds the link. It is also necessary to have links already in the mapper for tree data
because the tree stores the link in it's historic data, and hands them out without consulting the mapper, which means if
the mapper doesn't have the link the tree object will not be found (via that link).

So when a new shards database is populated and pushed into production we need to add all the objects in that shard to the
mapper in a batch operation.

== How to

The process is basically to use the postgresql postgres_fwd, and import foreign schema extensions to add the new shard
as a schema to the mappers database then insert the urls (match) identifiers and link them all up for each object type:

* name
* instance
* author
* reference
* tree_version
* tree_version_element


This code creates a database link for the shard to to mapper database.

WARNING: replace the things in square brackets [...] with an appropriate value.

[source]
.link_to_shard.sql
----
CREATE EXTENSION postgres_fdw;

CREATE SERVER [new_shard_server]
  FOREIGN DATA WRAPPER postgres_fdw
  OPTIONS (host '[127.0.0.1]', port '[5432]', dbname '[new_shard]');

CREATE USER MAPPING FOR nsl
  SERVER algae_server
  OPTIONS (user '[a_super_user]', password '[secret_passowrd]');

create schema [new_shard];

import foreign schema public from server [new_shard_server] into algae;

-- check connection
select count(*) from [new_shard].tree_version_element;
----

To make our life a little easier we're going to add a column onto the mapper.match table to add aback reference to the
identifier we want to match:

[source]
.add_temp.sql
----
-- make a temp column on match to link back to the identifier
alter table mapper.match add column temp bigint;
----


== Example, import fungi

Here is the example of the import for the 'fungi' shard (and schema name). To use this on another shard just replace
'fungi' with the desired name_space (or shard name).

[source]
.import-fungi-links.sql
----

...

-- check connection
select count(*) from fungi.name;

create index if not exists identifier_type_space_idx on mapper.identifier (object_type, name_space);

-- make a temp column on match to link back to the identifier
alter table mapper.match add column temp bigint;

-- Import names

select * from mapper.identifier where name_space = 'fungi' and object_type = 'name';

-- insert name identifiers
INSERT INTO mapper.identifier (id, id_number, version_number, name_space, object_type, deleted, reason_deleted, updated_at, updated_by, preferred_uri_id)
SELECT nextval('mapper.mapper_sequence'), id, null, 'fungi', 'name', FALSE,
       NULL, now(), 'import', NULL
FROM fungi.name;

INSERT INTO mapper.identifier (id, id_number, version_number, name_space, object_type, deleted, reason_deleted, updated_at, updated_by, preferred_uri_id)
SELECT nextval('mapper.mapper_sequence'), id, null, 'fungi', 'instance', FALSE,
       NULL, now(), 'import', NULL
FROM fungi.instance;

INSERT INTO mapper.identifier (id, id_number, version_number, name_space, object_type, deleted, reason_deleted, updated_at, updated_by, preferred_uri_id)
SELECT nextval('mapper.mapper_sequence'), id, null, 'fungi', 'author', FALSE,
       NULL, now(), 'import', NULL
FROM fungi.author;

INSERT INTO mapper.identifier (id, id_number, version_number, name_space, object_type, deleted, reason_deleted, updated_at, updated_by, preferred_uri_id)
SELECT nextval('mapper.mapper_sequence'), id, null, 'fungi', 'reference', FALSE,
       NULL, now(), 'import', NULL
FROM fungi.reference;

-- make urls
INSERT INTO mapper.match (id, uri, deprecated, updated_at, updated_by, temp)
SELECT nextval('mapper.mapper_sequence'), (object_type || '/fungi/' || id_number :: TEXT), FALSE,
       now(), 'pmcneil', i.id
FROM mapper.identifier i
WHERE i.name_space = 'fungi'
and i.version_number is null
and not exists (select 1 from mapper.match where uri = (object_type || '/fungi/' || id_number :: TEXT));

-- Import tree elements

INSERT INTO mapper.identifier (id, id_number, version_number, name_space, object_type, deleted, reason_deleted, updated_at, updated_by, preferred_uri_id)
SELECT nextval('mapper.mapper_sequence'), tree_element_id, tree_version_id, 'fungi', 'treeElement', FALSE,
       NULL, now(), 'pmcneil', NULL
FROM fungi.tree_version_element;

-- make treeElement urls
INSERT INTO mapper.match (id, uri, deprecated, updated_at, updated_by, temp)
SELECT nextval('mapper.mapper_sequence'), ('tree/' || version_number || '/' || id_number :: TEXT), FALSE,
       now(), 'pmcneil', i.id
FROM mapper.identifier i
WHERE i.object_type = 'treeElement'
  AND i.name_space = 'fungi'
  and not exists (select 1 from mapper.match where uri = ('tree/' || version_number || '/' || id_number :: TEXT));

--set the preferred uris of the identifiers
create index match_temp_idx on mapper.match (temp);
UPDATE mapper.identifier i
SET preferred_uri_id = m.id
FROM mapper.match m
WHERE i.preferred_uri_id is null
  AND i.name_space = 'fungi'
  AND m.updated_at > now() - interval '20 minutes'
  AND m.temp = i.id;

-- insert identifier_identities
INSERT INTO
  mapper.identifier_identities (match_id, identifier_id)
SELECT m.id, i.id
FROM mapper.identifier i
       JOIN mapper.match m ON i.preferred_uri_id = m.id
WHERE i.name_space = 'fungi'
  and m.temp is not null
  AND NOT exists(SELECT 1
                 FROM mapper.identifier_identities ii
                 WHERE ii.identifier_id = i.id AND ii.match_id = m.id);

-- and add the default hosts
INSERT INTO mapper.match_host (match_hosts_id, host_id)
SELECT m.id, (SELECT h.id FROM mapper.host h WHERE h.preferred)
FROM mapper.match m
WHERE m.temp is not null
  and NOT exists(SELECT 1
                 FROM mapper.match_host mh
                 WHERE mh.match_hosts_id = m.id);

-- remove any duplicate identifiers
delete from mapper.identifier
where name_space = 'fungi'
  and preferred_uri_id is null;

drop index mapper.match_temp_idx;
alter table mapper.match drop column temp;

VACUUM ANALYSE;

drop schema fungi cascade;

-----------8<----------
----


