= NSL Services development documentation
v1.0, October 2019
:doctype: book
:imagesdir: resources/images/
:toc: left
:toclevels: 4
:toc-class: toc2
:icons: font
:iconfont-cdn: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css
:stylesdir: resources/style/
:stylesheet: asciidoctor.css
:description: Services Configuration
:keywords: documentation, NSL, docker, configuration
:links:
:numbered:

The NSL services project is Taxanomic Name Infrastructure and is currently in use by The Australian Plant Name Index and
Australian Plant Census.

== What is this?

This is a scrapbook of documentation put together during the development of the NSL services. In here you will find the
change logs, notes, documentation about new (at the time) data structures for specific purposes. This is here to provide
a background on _why_ things were developed in the way they were and give you insight into how we expect it to work.

Much of the documentation is written in a timeline fashion, where later discoveries and updates will be below the initial
documentation.

We will try to keep newer things at the top of this book.

include::changelog.adoc[]

include::config.adoc[]

include::docker.adoc[]

include::Grails3-upgrade.adoc[]

include::distribution.adoc[]

include::merge-tree.adoc[]

include::createMapperLinksFromShard.adoc[]

include::name-construction.adoc[]

include::tree/ImprovementIdeas.adoc[]

include::tree/placement-rules.adoc[]

include::tree/TreeOperations.adoc[]

include::tree/archive/TreeStructure2-development.adoc[]