server:
  name: services-g5
grails:
  config:
    locations:
      - file:./services-g5-config.groovy
      - ~/.nsl/services-g5-config.groovy
  profile: web
  codegen:
    defaultPackage: au.org.biodiversity.nsl
  gorm:
    failOnError: true
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
#    allow-bean-definition-overriding: true  # Workaround for some grails 5 tomcat deploy issue
#    allow-circular-references: true  # Workaround for some grails 5 tomcat deploy issue
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true
    unique-names: true

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
  web:
    url:
      converter: 'hyphenated'
  assets:
    minifyCss: false
    minifyJs: false
  exceptionresolver:
    params:
      exclude:
        - password
        - creditCard
  cors:
    enabled: true
---
hibernate:
  flush:
    mode: commit
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

---
grails:
  gorm:
    failOnError: true


environments:
  development:
    grails:
#      serverURL: /
#      serverURL: /nsl/services

dataSource:
  pooled: true
  jmxExport: true
  dialect: au.org.biodiversity.nsl.ExtendedPostgreSQLDialect
  formatSql: false
  logSql: false
  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
